npz: ~/logs/real_exp/Pra_optuna_param_5_1/val_result/val_iter014276.npz
fs: 16000
seeds: [0]
long_noise_seconds: 100.0

stft_grid:
  - {nfft: 512,  hop: 256,  win: hann}
  - {nfft: 512,  hop: 256,  win: none}
  - {nfft: 1024, hop: 512,  win: hann}
  - {nfft: 1024, hop: 512,  win: none}

T_use_list: [16, 32, 64, 128, 256]

# ← この項目は削除
# slide_hop_frames: null

outdir: ~/avr_tuning_logs/pra_optuna/whitenoise_long/exp1
algo_name: NormMUSIC
mic_radius: 0.0365
force: false
